### ISSUE TITLE
HTTPS proxy support?

### ISSUE THREAD

**Issue by dmdeller** [excon/excon#342]
I am searching for a Ruby HTTP library that will allow me to connect to servers via an HTTPS proxy. So far, support for this seems almost non-existent at the client level - even curl (as far as I can tell) doesn't support it, although I have a Squid server up and running that [claims][1] to support this feature. (I've written off any flavour of SOCKS - there seems to be no SSL support at the protocol level.)

Firstly, does excon already support this? If so, I probably have my server configured wrong (it is very hard to tell, given the level of client support!).

If not, I would like to attempt to add this feature to excon. This is very much outside my comfort zone, so any pointers on where to start would be appreciated. I'm looking at excon specifically because the code seems pretty clean and easy to understand in comparison to others.

Based on the following backtrace, I theorise that excon is attempting to connect to my proxy over HTTP, based on the fact that it is using `socket.rb` instead of `ssl_socket.rb`. Does that seem right?

    Excon.get('http://www.google.com', :proxy => 'https://user:pass@my-proxy.example.com:3129')
    Excon::Errors::SocketError: Connection reset by peer (Errno::ECONNRESET)
    	from /.../excon-0.30.0/lib/excon/socket.rb:38:in `read_nonblock'
    	from /.../excon-0.30.0/lib/excon/socket.rb:38:in `read'
    	from /.../excon-0.30.0/lib/excon/socket.rb:92:in `readline'
    	from /.../excon-0.30.0/lib/excon/response.rb:34:in `parse'
    	from /.../excon-0.30.0/lib/excon/middlewares/response_parser.rb:6:in `response_call'
    	from /.../excon-0.30.0/lib/excon/connection.rb:387:in `response'
    	from /.../excon-0.30.0/lib/excon/connection.rb:268:in `request'
    	from /.../excon-0.30.0/lib/excon.rb:244:in `get'
    	from (irb):9
    	from /.../ruby/bin/irb:12:in `<main>'

[1]: http://www.squid-cache.org/Doc/config/https_port/

**Comment by geemus** [comment]
Closing due to inactivity. Please let me know if you have further questions.
