### ISSUE TITLE
OpenSSL::SSL::SSLError and Timeouts

### ISSUE THREAD

**Issue by eljojo** [excon/excon#415]
Hi, thanks for Excon, I really like it :)

I am doing a request using the following code:
```ruby
opts = {
  proxy: proxy,
  middlewares: Excon.defaults[:middlewares] + [Excon::Middleware::RedirectFollower],
  connect_timeout: 15,
  read_timeout: 15
}
request = Excon.get(url, opts)
```
``proxy`` is a random http proxy in the form of ``http://123.4.5.6:443``

About one every ten requests fails with something along the lines of:
```
SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)
```

What baffles me is that **it fails after 60 seconds**, instead of 15.
I thought it was a problem specific to one proxy, but seems to be happening randomly for my proxy list.
In any case, the **timeout should cancel the request before the 60 seconds**, right?

PS: this happens even without the RedirectFollower middleware.

**UPDATE 1**: The problem IS caused by one specific proxy.

Traceback:
```
2014-08-08T12:09:55.158Z 10 TID-ox5rzdlhk ResultPageWorker JID-681f73d5e2499373752287c1 INFO: fail: 59.633 sec
2014-08-08T12:09:55.162Z 10 TID-ox5rzdlhk WARN: {"retry"=>true, "queue"=>"default", "class"=>"ResultPageWorker", "args"=>[52, 6], "jid"=>"681f73d5e2499373752287c1", "enqueued_at"=>1407498727.8573818, "error_message"=>"SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)", "error_class"=>"Excon::Errors::SocketError", "failed_at"=>1407499795.1571, "retry_count"=>0}
2014-08-08T12:09:55.164Z 10 TID-ox5rzdlhk WARN: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)
2014-08-08T12:09:55.165Z 10 TID-ox5rzdlhk WARN: /app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon/ssl_socket.rb:105:in `connect_nonblock'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon/ssl_socket.rb:105:in `block in initialize'
/app/vendor/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/app/vendor/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
/app/vendor/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:35:in `catch'
/app/vendor/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:35:in `catch'
/app/vendor/ruby-2.1.2/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon/ssl_socket.rb:101:in `initialize'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon/connection.rb:414:in `new'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon/connection.rb:414:in `socket'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon/connection.rb:126:in `request_call'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon/middlewares/base.rb:15:in `request_call'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon/middlewares/mock.rb:44:in `request_call'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon/middlewares/base.rb:15:in `request_call'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon/middlewares/base.rb:15:in `request_call'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon/middlewares/base.rb:15:in `request_call'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon/connection.rb:269:in `request'
/app/vendor/bundle/ruby/2.1.0/gems/excon-0.38.0/lib/excon.rb:244:in `get'
```

**Comment by geemus** [comment]
Closing due to inactivity. Please let me know if you have further questions.
