### ISSUE TITLE
uninitialized constant Excon (NameError)

### ISSUE THREAD

**Issue by ericbrooke** [excon/excon#424]
/Users/ericbrooke/dev/mybesthelper/config/initializers/excon.rb:1:in `<top (required)>': uninitialized constant Excon (NameError)

```
Excon.defaults[:write_timeout] = 500
```

When I comment out this line, my local env works.  I am using this as a dependancy for Mandrill

here is the stack trace:
```
/Users/ericbrooke/dev/mybesthelper/config/initializers/excon.rb:1:in `<top (required)>': uninitialized constant Excon (NameError)
from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/engine.rb:648:in `block in load_config_initializer'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/activesupport-4.1.5/lib/active_support/notifications.rb:161:in `instrument'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/engine.rb:647:in `load_config_initializer'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/engine.rb:611:in `each'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/initializable.rb:30:in `run'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/initializable.rb:44:in `each'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:411:in `call'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/application.rb:300:in `initialize!'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/railtie.rb:194:in `public_send'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/railtie.rb:194:in `method_missing'
	from /Users/ericbrooke/dev/mybesthelper/config/environment.rb:20:in `<top (required)>'
	from /Users/ericbrooke/dev/mybesthelper/config.ru:4:in `block in <main>'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
	from /Users/ericbrooke/dev/mybesthelper/config.ru:in `new'
	from /Users/ericbrooke/dev/mybesthelper/config.ru:in `<main>'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/commands/server.rb:50:in `app'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/commands/server.rb:130:in `log_to_stdout'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/commands/server.rb:67:in `start'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:81:in `block in server'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/ericbrooke/.rvm/gems/ruby-2.1.2@mbh/gems/railties-4.1.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by geemus** [comment]
Closing due to inactivity, please let me know if this is still a problem or I can help.
