### ISSUE TITLE
Excon::Errors::SocketError with Ruby 2.2.1

### ISSUE THREAD

**Issue by MSchmidt** [excon/excon#482]
excon failing to load with ruby 2.2.1

```
/Users/matt/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/excon-0.44.3/lib/excon/socket.rb:143:in `rescue in rescue in block in connect': break from proc-closure (LocalJumpError) (Excon::Errors::SocketError)
	from /Users/matt/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/excon-0.44.3/lib/excon/socket.rb:137:in `rescue in block in connect'
```

**Comment by geemus** [comment]
I loosened travis so it can at least in theory start doing this (looks like maybe they don't have 2.2.1 yet). I also just pushed a fix that I think should help, but lack an easy way to try it just now. Let me know if you have better luck and I can probably follow up with a release shortly.

**Comment by MSchmidt** [comment]
Can confirm that the commit fixes my issue and everything my project makes use of works fine now.

**Comment by ain** [comment]
I can also confirm this to work and resolve interactive-pioneers/maileon#4 in our case.

@geemus any chance for `0.44.4` today?

**Comment by geemus** [comment]
Thanks for verifying, just pushed 0.44.4 with the fix.

**Comment by ain** [comment]
Thanks a lot for a prompt reaction, you made my release! :+1:

**Comment by geemus** [comment]
Glad to help!

**Comment by groky** [comment]
Nice fix. Thanks @geemus

**Comment by kyletolle** [comment]
This was very helpful for me, and the fix worked too!

**Comment by gurgelrenan** [comment]
This solved a problem with mandrill-api gem too. Thanks!

**Comment by emilesilvis** [comment]
Getting this again with excon 0.45.1 and Ruby 2.2.1.

Here is part of the stack trace:

```
Excon::Errors::SocketError: break from proc-closure (LocalJumpError)
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/socket.rb:209:in `rescue in rescue in block in connect'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/socket.rb:202:in `rescue in block in connect'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/socket.rb:172:in `block in connect'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/socket.rb:168:in `each'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/socket.rb:168:in `connect'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/ssl_socket.rb:151:in `connect'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/socket.rb:28:in `initialize'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/ssl_socket.rb:9:in `initialize'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/connection.rb:380:in `new'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/connection.rb:380:in `socket'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/connection.rb:105:in `request_call'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/middlewares/mock.rb:47:in `request_call'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/middlewares/base.rb:15:in `request_call'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/middlewares/base.rb:15:in `request_call'
	from /Users/emilesilvis/.rvm/gems/ruby-2.2.1/gems/excon-0.43.0/lib/excon/middlewares/base.rb:15:in `request_call'
```

**Comment by geemus** [comment]
@emilesilvis the stacktrace appears to indicate it is still using excon-0.43.0, which would be pre-fix, could you try bumping and see if it clears up? Thanks!

**Comment by emilesilvis** [comment]
@geemus sorry my bad, that was the issue :disappointed: Thanks!

**Comment by geemus** [comment]
No worries, dependencies are always tricky/finicky, glad to here that resolved it for you.
