### ISSUE TITLE
"local port can be re-bound" test fails

### ISSUE THREAD

**Issue by voxik** [excon/excon#497]
I am trying to update rubygem-excond package on Fedora, but since F22+ I observe following error:

```
  Excon basics (reusable local port)
    has a local port + returns true
    local port can be re-bound - returns "xxxxxxxxxx"
    Connection refused - connect(2) for 10.34.4.232:9292 (Errno::ECONNREFUSED)
      tests/basic_tests.rb:271:in `connect'
      tests/basic_tests.rb:271:in `connect'
      tests/basic_tests.rb:311:in `block (3 levels) in <top (required)>'
      /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:140:in `instance_eval'
      /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:140:in `assert'
      /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:112:in `returns'
      tests/basic_tests.rb:303:in `block (2 levels) in <top (required)>'
      tests/test_helper.rb:242:in `with_rackup'
      tests/basic_tests.rb:292:in `block in <top (required)>'
      /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
      /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
      /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:38:in `initialize'
      /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:13:in `new'
      /usr/share/gems/gems/shindo-0.3.8/lib/shindo.rb:13:in `tests'
      tests/basic_tests.rb:256:in `<top (required)>'
      /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `load'
      /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `block (2 levels) in run_in_thread'
      /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `each'
      /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `block in run_in_thread'
    Action? [c,q,r,?]? q
```

However, when I downgrade Rack to version 1.5.2, instead of standard 1.6.0, the test suite is passing just fine. Do you have, by a chance, any idea what might be the reason. It seems that your Travis test are passing just fine with Rack 1.6.0, but there are other differences in gem versions in yours and mine environment:

```
$ rpm -q ruby
ruby-2.2.1-10.fc23.x86_64

$ gem list

*** LOCAL GEMS ***

activesupport (4.2.1)
bigdecimal (1.2.6)
chronic (0.10.2)
delorean (2.0.0)
eventmachine (1.0.6)
formatador (0.2.4)
i18n (0.7.0)
io-console (0.4.3)
json (1.8.2)
minitest (5.4.3)
open4 (1.3.4)
psych (2.0.8)
rack (1.6.0, 1.5.2)
rack-protection (1.5.3)
rdoc (4.2.0)
shindo (0.3.8)
sinatra (1.4.5)
thread_safe (0.3.5)
tilt (1.4.1)
tzinfo (1.2.2)
```

**Comment by geemus** [comment]
I also saw this come through on travis (but just once, and when I retried the build it passed). So I'm not sure if it is a version related thing or a race condition or what. Are you seeing it consistently?

**Comment by voxik** [comment]
Well, I thought about possible race condition, since it works on travis, but it newer worked for me with rack 1.6.0 and always worked with 1.5.2. I;d like to try to run just this single test, but I don't know how to do it with shindo.

**Comment by geemus** [comment]
Yeah, I'm not sure there is an easy way to run just one test. Maybe copy/paste the file and then just delete the other tests?
