### ISSUE TITLE
Excon Error: can't convert nil into String

### ISSUE THREAD

**Issue by ilackarms** [excon/excon#524]
Sending the following request through excon:
```
excon.request {:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>600, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.27.0 fog-core/1.32.0", "Content-Type"=>"application/json", "Accept"=>"application/json", "X-Auth-Token"=>"5afc2d4c97c940678763c25e359bc0a5", "Host"=>"pivotal-1.openstack.blueboxgrid.com:8777"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>180, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.4 (x86_64-linux) ruby/1.9.3", :write_timeout=>180, :host=>"pivotal-1.openstack.blueboxgrid.com", :hostname=>"pivotal-1.openstack.blueboxgrid.com", :path=>"/v2/5552c272e58e4127ae5457990d82005c/images/detail.json", :port=>8777, :query=>{}, :scheme=>"https", :instrumentor=>Bosh::OpenStackCloud::ExconLoggingInstrumentor, :expects=>[200, 203], :method=>"GET", :retries_remaining=>4, :connection=>#<Excon::Connection:2cd36e0 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>600, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.27.0 fog-core/1.32.0"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>180, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.4 (x86_64-linux) ruby/1.9.3", :write_timeout=>180, :host=>"pivotal-1.openstack.blueboxgrid.com", :hostname=>"pivotal-1.openstack.blueboxgrid.com", :path=>"", :port=>8777, :query=>nil, :scheme=>"https", :instrumentor=>Bosh::OpenStackCloud::ExconLoggingInstrumentor} @socket_key="https://pivotal-1.openstack.blueboxgrid.com:8777">, :stack=>#<Excon::Middleware::ResponseParser:0x000000034add70 @stack=#<Excon::Middleware::Expects:0x000000034add98 @stack=#<Excon::Middleware::Idempotent:0x000000034addc0 @stack=#<Excon::Middleware::Instrumentor:0x000000034ade10 @stack=#<Excon::Middleware::Mock:0x000000034ade38 @stack=#<Excon::Connection:2cd36e0 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>600, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.27.0 fog-core/1.32.0"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>false, :read_timeout=>180, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.4 (x86_64-linux) ruby/1.9.3", :write_timeout=>180, :host=>"pivotal-1.openstack.blueboxgrid.com", :hostname=>"pivotal-1.openstack.blueboxgrid.com", :path=>"", :port=>8777, :query=>nil, :scheme=>"https", :instrumentor=>Bosh::OpenStackCloud::ExconLoggingInstrumentor} @socket_key="https://pivotal-1.openstack.blueboxgrid.com:8777">>>>>>}
```

returns error:
```
excon.error {:error=>#<Excon::Errors::SocketError: can't convert nil into String (TypeError)>}
```

This appears to happen in multiple places in our code:
```
[cpiCmdRunner] 2015/08/05 22:37:27 DEBUG - Rescued Unknown: can't convert nil into String (TypeError). backtrace: /root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/excon-0.45.4/lib/excon/response.rb:141:in `parse'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:6:in `response_call'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/fog-core-1.32.0/lib/fog/core/connection.rb:81:in `request'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/fog-1.27.0/lib/fog/openstack/compute.rb:343:in `request'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/fog-1.27.0/lib/fog/openstack/requests/compute/list_images_detail.rb:10:in `list_images_detail'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/fog-1.27.0/lib/fog/openstack/models/compute/images.rb:21:in `all'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/fog-core-1.32.0/lib/fog/core/collection.rb:113:in `lazy_load'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/fog-core-1.32.0/lib/fog/core/collection.rb:24:in `each'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_openstack_cpi-1.3016.0/lib/cloud/openstack/cloud.rb:252:in `find'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_openstack_cpi-1.3016.0/lib/cloud/openstack/cloud.rb:252:in `block (2 levels) in create_vm'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_openstack_cpi-1.3016.0/lib/cloud/openstack/helpers.rb:26:in `with_openstack'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_openstack_cpi-1.3016.0/lib/cloud/openstack/cloud.rb:252:in `block in create_vm'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_common-1.3016.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_openstack_cpi-1.3016.0/lib/cloud/openstack/cloud.rb:236:in `create_vm'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_cpi-1.3016.0/lib/bosh/cpi/cli.rb:70:in `public_send'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_cpi-1.3016.0/lib/bosh/cpi/cli.rb:70:in `run'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/bosh_openstack_cpi-1.3016.0/bin/openstack_cpi:20:in `<top (required)>'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/bin/openstack_cpi:16:in `load'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/bin/openstack_cpi:16:in `<main>'
 Failed (00:02:36)
Failed deploying (00:02:36)
```
```
expected Bosh::Clouds::VMCreationFailed with message matching /Floating IP 255.255.255.255 not allocated/, got #<Excon::Errors::SocketError: no implicit conversion of nil into String (TypeError)> with backtrace:
         # ./lib/cloud/openstack/cloud.rb:233:in `find'
         # ./lib/cloud/openstack/cloud.rb:233:in `block (2 levels) in create_vm'
         # ./lib/cloud/openstack/helpers.rb:26:in `with_openstack'
         # ./lib/cloud/openstack/cloud.rb:233:in `block in create_vm'
         # /tmp/build/6d37ae7f-c811-4cd4-5f36-1ede85c2171f/bosh-src/bosh_common/lib/common/thread_formatter.rb:49:in `with_thread_name'
         # ./lib/cloud/openstack/cloud.rb:217:in `create_vm'
         # ./spec/integration/lifecycle_spec.rb:280:in `create_vm'
         # ./spec/integration/lifecycle_spec.rb:256:in `block (4 levels) in <top (required)>'
         # ./spec/integration/lifecycle_spec.rb:255:in `block (3 levels) in <top (required)>'
     # ./spec/integration/lifecycle_spec.rb:255:in `block (3 levels) in <top (required)>'
```
```
Rescued Unknown: can't convert nil into String (TypeError). backtrace: /root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/excon-0.45.4/lib/excon/response.rb:141:in `parse'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:6:in `response_call'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/fog-core-1.32.0/lib/fog/core/connection.rb:81:in `request'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/fog-1.27.0/lib/fog/openstack/compute.rb:343:in `request'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/fog-1.27.0/lib/fog/openstack/requests/compute/list_images_detail.rb:10:in `list_images_detail'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/fog-1.27.0/lib/fog/openstack/models/compute/images.rb:21:in `all'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/fog-core-1.32.0/lib/fog/core/collection.rb:113:in `lazy_load'
/root/.bosh_init/installations/ea1fb615-10b7-4d63-7153-6cbca428059f/packages/bosh_openstack_cpi/gem_home/ruby/1.9.1/gems/fog-core-1.32.0/lib/fog/core/collection.rb:24:in `each'
```

What is the intended behavior of this error? What could be causing it?

**Comment by ilackarms** [comment]
additional failure logs if necessary:
https://main.bosh-ci.cf-app.com/pipelines/openstack-cpi/jobs/lifecycle/builds/86

**Comment by geemus** [comment]
It's not an error I would expect to see. Basically, when it gets the response, it tries to read either 1MB or the remaining length at a time until all data has been read. For some reason here, it is doing a read and getting back nil (even though, according to content-length there should be more to read). My (rough) guess would be that the server is actually mis-reporting content-length so that we try to read beyond the end of the response, but I could be wrong. In any event, this is definitely not a common failure pattern for excon (which is used pretty heavily across a lot of other different services). Hope that helps, but certainly happy to discuss further.

**Comment by punkle** [comment]
Interesting coincidence. I am seeing the same issue. It appears that the issue also when calling the image.json API of openstack. In my case GETting `/v2/tenant-id/images/detail.json?status=ACTIVE`. In my case however, I am using the Fog library which uses Excon under the hood. It is intermittent.

**Comment by geemus** [comment]
Closing due to inactivity and not enough info to go on. Please let me know if this is still an issue or if there is anything I can help with.
