### ISSUE TITLE
https requests result in: "no cipher match (OpenSSL::SSL::SSLError)"

### ISSUE THREAD

**Issue by atambo** [excon/excon#528]
I am using jruby-1.7.22 and I am able to make https requests using the ruby standard library "net/https" like so:

```ruby
require "net/https"
require "uri"

uri = URI.parse("https://google.com")
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE

request = Net::HTTP::Get.new(uri.request_uri)

response = http.request(request)
response.body
```

But when I try to make the same https request using Excon with the following code:

```ruby
response = Excon.get("https://google.com")
response.body
```

I get the following error:

```
no cipher match (OpenSSL::SSL::SSLError)
org/jruby/ext/openssl/SSLContext.java:500:in `ciphers='
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/ssl_socket.rb:24:in `initialize'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/connection.rb:387:in `socket'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/connection.rb:106:in `request_call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/middlewares/mock.rb:47:in `request_call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/middlewares/base.rb:15:in `request_call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon/connection.rb:233:in `request'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/excon-0.45.3.cookies/lib/excon.rb:233:in `get'
(eval):1:in `(eval)'
org/jruby/RubyBasicObject.java:1598:in `instance_eval'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/app/models/admin/endpoint.rb:37:in `evaluate'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/app/controllers/admin/endpoints_controller.rb:70:in `test'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/abstract_controller/base.rb:189:in `process_action'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_controller/metal/rendering.rb:10:in `process_action'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/abstract_controller/callbacks.rb:20:in `process_action'
org/jruby/RubyProc.java:271:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.12/lib/active_support/callbacks.rb:113:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.12/lib/active_support/callbacks.rb:552:in `compile'
org/jruby/RubyProc.java:271:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.12/lib/active_support/callbacks.rb:502:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.12/lib/active_support/callbacks.rb:86:in `run_callbacks'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/abstract_controller/callbacks.rb:19:in `process_action'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_controller/metal/rescue.rb:29:in `process_action'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_controller/metal/instrumentation.rb:31:in `process_action'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.12/lib/active_support/notifications.rb:159:in `instrument'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.12/lib/active_support/notifications/instrumenter.rb:19:in `instrument'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.12/lib/active_support/notifications.rb:159:in `instrument'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/abstract_controller/base.rb:136:in `process'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionview-4.1.12/lib/action_view/rendering.rb:30:in `process'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_controller/metal.rb:196:in `dispatch'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_controller/metal.rb:232:in `action'
org/jruby/RubyProc.java:271:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/routing/route_set.rb:50:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/journey/router.rb:73:in `call'
org/jruby/RubyArray.java:1613:in `each'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/journey/router.rb:59:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/routing/route_set.rb:692:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.5/lib/rack/conditionalget.rb:35:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/middleware/flash.rb:254:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/middleware/cookies.rb:562:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/middleware/callbacks.rb:29:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.12/lib/active_support/callbacks.rb:82:in `run_callbacks'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/railties-4.1.12/lib/rails/rack/logger.rb:38:in `call_app'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/railties-4.1.12/lib/rails/rack/logger.rb:22:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/actionpack-4.1.12/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/activesupport-4.1.12/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/railties-4.1.12/lib/rails/engine.rb:514:in `call'
/opt/ibm/WEX-appbuilder/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/WEB-INF/gems/gems/railties-4.1.12/lib/rails/application.rb:144:in `call'
classpath:/rack/handler/servlet.rb:22:in `call'
```

**Comment by geemus** [comment]
Hey, sorry to hear you are having trouble here. The issue may have to do with OpenSSL and/or JRuby versions (so if you aren't up to date, that might be an easy thing to try). Otherwise, we attempt to set a cipher setting to ensure higher security, by default the cipher setting we use is:

`'HIGH:!SSLv2:!aNULL:!eNULL:!3DES'` (see [constants.rb](https://github.com/excon/excon/blob/master/lib/excon/constants.rb#L112))

It may be that one or more of those is not supported in your setup (they are colon delimited), so you could try tweaking it to ascertain which one (or ones) are failing. I'm reticent to change it directly at this time since others have not reported issues and the suggested settings came from a trusted security person (whereas I personally don't know that much about which settings would be preferred).

Hope that helps narrow it down at least, but definitely let me know if you need further help.

**Comment by atambo** [comment]
Thanks for pointing me in the right direction! When I use:

```ruby
Excon.defaults[:ciphers] = 'DEFAULT'
```

Things work again. It looks like jruby uses ```"AES:ALL:!aNULL:!eNULL:+RC4:@STRENGTH"``` as it's default cipher string.

**Comment by atambo** [comment]
Here is the reference to where jruby sets it:

https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/CipherStrings.java#L184

and I think MRI ruby sets it here:

https://github.com/ruby/ruby/blob/24da2db3e1eab67b6ee7be00d75b73beb273a4c4/ext/openssl/lib/openssl/ssl.rb#L26

**Comment by geemus** [comment]
Cool, thanks for the references. Glad to hear you got it working.
