### ISSUE TITLE
Socket operation on non-socket - connect(2) (Errno::ENOTSOCK) 

### ISSUE THREAD

**Issue by JoshMcKin** [excon/excon#534]
Using Ruby 2.2.3 on heroku, I've configured Excon in a connection pool with: 

     @@excon_settings =   {:idempotent => true,
                       :thread_safe_sockets => false,
                      :persistent => true,
                      :retry_limit => 2,
                      :connect_timeout => 10,
                      :read_timeout => 10,
                      :write_timeout => 10}

On occasion we are getting `Socket operation on non-socket - connect(2) (Errno::ENOTSOCK) ` errors with the backtrace posted below. 

Not sure if this is the result of a flakey webservice but thought I'd start here since the webservice author says their site is always up :| .

Looking at the code it resembles what the ruby [doc](http://ruby-doc.org/stdlib-2.2.3/libdoc/socket/rdoc/Socket.html#method-i-connect_nonblock) suggests so its entirely possible its nothing to do with Excon.

Suggestions?

```
/app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/socket.rb:142:in `connect_nonblock' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/socket.rb:142:in `rescue in block in connect' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/socket.rb:119:in `block in connect' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/socket.rb:110:in `each' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/socket.rb:110:in `connect' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/ssl_socket.rb:148:in `connect' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/socket.rb:28:in `initialize' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/ssl_socket.rb:8:in `initialize' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/connection.rb:387:in `new' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/connection.rb:387:in `socket' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/connection.rb:106:in `request_call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/excon/middleware.rb:30:in `request_call' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/middlewares/mock.rb:47:in `request_call' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/middlewares/instrumentor.rb:22:in `request_call' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/connection.rb:233:in `request' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb:26:in `error_call' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/middlewares/base.rb:10:in `error_call' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/connection.rb:256:in `rescue in request' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/connection.rb:204:in `request' /app/vendor/bundle/ruby/2.0.0/gems/excon-0.45.4/lib/excon/connection.rb:297:in `get' /app/vendor/gems/vtx_payments/app/models/basic_msp_loan.rb:2028:in `block in http_get' /app/vendor/bundle/ruby/2.0.0/gems/hot_tub-0.2.6/lib/hot_tub/pool.rb:50:in `call' /app/vendor/bundle/ruby/2.0.0/gems/hot_tub-0.2.6/lib/hot_tub/pool.rb:50:in `run' /app/vendor/gems/vtx_payments/app/models/basic_msp_loan.rb:2027:in `http_get' /app/vendor/gems/vtx_payments/app/models/basic_msp_loan.rb:2101:in `fetch_msp_xml' /app/vendor/gems/vtx_payments/app/models/basic_msp_loan.rb:2044:in `fetch_response' /app/vendor/gems/vtx_payments/app/models/basic_msp_loan.rb:2037:in `response' /app/vendor/gems/vtx_payments/app/models/basic_msp_loan.rb:1947:in `authenticate_loan_data' /app/vendor/gems/vtx_payments/app/models/basic_msp_loan.rb:1884:in `process_login' /app/vendor/gems/msp_webpay/app/controllers/sessions_controller.rb:199:in `process_login' /app/vendor/gems/msp_webpay/app/controllers/sessions_controller.rb:27:in `login' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_controller/metal/implicit_render.rb:4:in `send_action' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/abstract_controller/base.rb:167:in `process_action' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_controller/metal/rendering.rb:10:in `process_action' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/abstract_controller/callbacks.rb:18:in `block in process_action' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:591:in `block in _run__3467881876886841674__process_action__873155282887808389__callbacks' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_2175' /app/vendor/gems/msp_webpay/app/controllers/msp_webpay_application_controller.rb:125:in `block in wrap_in_slave_cache' /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/query_cache.rb:26:in `cache' /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.22/lib/active_record/query_cache.rb:10:in `cache' /app/vendor/gems/msp_webpay/app/controllers/msp_webpay_application_controller.rb:124:in `wrap_in_slave_cache' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_2175' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:513:in `_run__3467881876886841674__process_action__873155282887808389__callbacks' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405:in `__run_callback' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:81:in `run_callbacks' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/abstract_controller/callbacks.rb:17:in `process_action' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_controller/metal/rescue.rb:29:in `process_action' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `block in instrument' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `instrument' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_controller/metal/instrumentation.rb:29:in `process_action' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_controller/metal/params_wrapper.rb:207:in `process_action' /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.22/lib/active_record/railties/controller_runtime.rb:18:in `process_action' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:25:in `process_action' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/abstract_controller/base.rb:121:in `process' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/abstract_controller/rendering.rb:45:in `process' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_controller/metal.rb:203:in `dispatch' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_controller/metal.rb:246:in `block in action' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/routing/route_set.rb:73:in `call' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/routing/route_set.rb:73:in `dispatch' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/routing/route_set.rb:36:in `call' /app/vendor/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call' /app/vendor/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `each' /app/vendor/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `call' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/routing/route_set.rb:608:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/etag.rb:23:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/conditionalget.rb:35:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/head.rb:14:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/params_parser.rb:21:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/gems/msp_webpay/app/middlewares/vtx_middleware.rb:24:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/flash.rb:242:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context' /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/cookies.rb:341:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.22/lib/active_record/query_cache.rb:64:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405:in `_run__2031829868092686403__call__3378958491122945115__callbacks' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405:in `__run_callback' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:385:in `_run_call_callbacks' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:81:in `run_callbacks' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/callbacks.rb:27:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/remote_ip.rb:31:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.22/lib/rails/rack/logger.rb:32:in `call_app' /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.22/lib/rails/rack/logger.rb:16:in `block in call' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/tagged_logging.rb:22:in `tagged' /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.22/lib/rails/rack/logger.rb:16:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/request_id.rb:22:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.22/lib/active_support/cache/strategy/local_cache.rb:72:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.22/lib/action_dispatch/middleware/static.rb:83:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/rack-ssl-1.3.4/lib/rack/ssl.rb:27:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/rack-cache-1.5.0/lib/rack/cache/context.rb:140:in `forward' /app/vendor/bundle/ruby/2.0.0/gems/rack-cache-1.5.0/lib/rack/cache/context.rb:147:in `pass' /app/vendor/bundle/ruby/2.0.0/gems/rack-cache-1.5.0/lib/rack/cache/context.rb:159:in `invalidate' /app/vendor/bundle/ruby/2.0.0/gems/rack-cache-1.5.0/lib/rack/cache/context.rb:74:in `call!' /app/vendor/bundle/ruby/2.0.0/gems/rack-cache-1.5.0/lib/rack/cache/context.rb:51:in `call' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.22/lib/rails/engine.rb:484:in `call' /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.22/lib/rails/application.rb:231:in `call' /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing' /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call' /app/vendor/bundle/ruby/2.0.0/gems/puma-2.14.0/lib/puma/configuration.rb:78:in `call' /app/vendor/bundle/ruby/2.0.0/gems/puma-2.14.0/lib/puma/server.rb:541:in `handle_request' /app/vendor/bundle/ruby/2.0.0/gems/puma-2.14.0/lib/puma/server.rb:388:in `process_client' /app/vendor/bundle/ruby/2.0.0/gems/puma-2.14.0/lib/puma/server.rb:270:in `block in run' /app/vendor/bundle/ruby/2.0.0/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `call' /app/vendor/bundle/ruby/2.0.0/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by JoshMcKin** [comment]
Sorry I should have been more specific. Do you know what could cause Errno::ENOTSOCK after a Errno::EINPROGRESS?  The searching I've done has been fruitless and my Socket knowledge is unfortunately lacking.

**Comment by JoshMcKin** [comment]
After some digging I believe the issue is the initialization of the socket is taking longer than the timeout, event after the call to IO.select which will wait for the socket to connect or timeout so when `#connect_nonblock` is called again raises Errno::ENOTSOCK because the socket never connected.

**Comment by geemus** [comment]
Weird. Thanks for the detailed update, I have not heard about or encountered this before (that I recall anyway). Any idea why the init would be taking so long?

**Comment by JoshMcKin** [comment]
Its an old .Net app on an even older Windows server in a COLO, so I'm writing it off to internet gnomes :)

**Comment by geemus** [comment]
Haha, fair enough. Those damn gnomes!
