### ISSUE TITLE
302 causes SSL failure with "please set `Excon.defaults...

### ISSUE THREAD

**Issue by dogweather** [excon/excon#546]
Here's a script that demonstrates the problem:

``` ruby
require 'excon'

# Succeeds
Excon.head('https://www.bloc.io') # 200
puts 'Success with www.bloc.io'

# Should succeed, but fails, and with misleading error message
puts Excon.head('https://bloc.io') # 302
puts 'Success with bloc.io'
```

The output is:

```
$ ruby error-demo.rb
Success with www.bloc.io
/Users/robb/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `connect_nonblock': Unable to verify certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, `ENV['SSL_CERT_DIR'] = path_to_certs`, `Excon.defaults[:ssl_ca_file] = path_to_file`, `ENV['SSL_CERT_FILE'] = path_to_file`, `Excon.defaults[:ssl_verify_callback] = callback` (see OpenSSL::SSL::SSLContext#verify_callback), or `Excon.defaults[:ssl_verify_peer] = false` (less secure). (Excon::Errors::SocketError)
    from /Users/robb/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `initialize'
    from /Users/robb/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/excon-0.45.4/lib/excon/connection.rb:387:in `new'
    from /Users/robb/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/excon-0.45.4/lib/excon/connection.rb:387:in `socket'
    from /Users/robb/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/excon-0.45.4/lib/excon/connection.rb:106:in `request_call'
    from /Users/robb/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/excon-0.45.4/lib/excon/middlewares/mock.rb:47:in `request_call'
    from /Users/robb/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/excon-0.45.4/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
    from /Users/robb/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
    from /Users/robb/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
    from /Users/robb/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
    from /Users/robb/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/excon-0.45.4/lib/excon/connection.rb:233:in `request'
    from /Users/robb/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/excon-0.45.4/lib/excon.rb:229:in `head'
    from error-demo.rb:8:in `<main>'
```

Here are Httpie and Curl's results for this url:

```
$ http --headers https://bloc.io
HTTP/1.1 302 Found
Connection: Keep-Alive
Content-Length: 277
Content-Type: text/html; charset=iso-8859-1
Date: Tue, 16 Feb 2016 07:37:48 GMT
Keep-Alive: timeout=5, max=100
Location: https://www.bloc.io/
Server: Apache/2.4.7 (Ubuntu)

$ curl --head https://bloc.io
HTTP/1.1 302 Found
Date: Tue, 16 Feb 2016 07:38:25 GMT
Server: Apache/2.4.7 (Ubuntu)
Location: https://www.bloc.io/
Content-Type: text/html; charset=iso-8859-1
```

**Comment by geemus** [comment]
Are you sure the cert is broad enough to match both versions? Otherwise I wouldn't think the 302 itself should matter.
