### ISSUE TITLE
Excon::Error::Socket: end of file reached (EOFError)

### ISSUE THREAD

**Issue by baelter** [excon/excon#587]
I've seen a few old threads on this. But suggestions like calling reset on connection doesn't solve the issue. Any idea on what might be causing this?

```
#<Excon::Error::Socket: end of file reached (EOFError)>
19:16:04 worker.1 | end of file reached (EOFError)
19:16:04 worker.1 |   /Users/anders/.rbenv/versions/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:178:in `sysread_nonblock'
19:16:04 worker.1 |   /Users/anders/.rbenv/versions/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:178:in `read_nonblock'
19:16:04 worker.1 |   /Users/anders/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/excon-0.51.0/lib/excon/socket.rb:45:in `readline'
19:16:04 worker.1 |   /Users/anders/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/excon-0.51.0/lib/excon/response.rb:62:in `parse'
19:16:04 worker.1 |   /Users/anders/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/excon-0.51.0/lib/excon/middlewares/response_parser.rb:6:in `response_call'
19:16:04 worker.1 |   /Users/anders/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/excon-0.51.0/lib/excon/connection.rb:389:in `response'
19:16:04 worker.1 |   /Users/anders/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/excon-0.51.0/lib/excon/connection.rb:253:in `request'
19:16:04 worker.1 |   /Users/anders/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/excon-0.51.0/lib/excon/connection.rb:314:in `get'
```

**Comment by starbelly** [comment]
@baelter What is the use case in which this exception is happening?

**Comment by baelter** [comment]
```
@http = Excon.new('https://route53.amazonaws.com',
                      persistent: true,
                      headers: headers,
                      timeout: 60,
                      idempotent: true,
                      debug_response: true,
                      debug_request: true)

@http.get(path: "/#{API_VERSION}/hostedzone/#{HOST_ZONE_ID}/rrset",
                     query: query,
                     expects: 200)

def headers
    # date = @http.get(path: '/date').headers['Date']
    date = Time.now.utc.to_datetime.rfc822
    hmac = OpenSSL::HMAC.digest('sha256', ENV.fetch('AWS_SECRET_KEY'), date)
    sign = Base64.encode64(hmac).chomp
    key = ENV.fetch('AWS_ACCESS_KEY')
    auth = "AWS3-HTTPS AWSAccessKeyId=#{key},Algorithm=HmacSHA256,Signature=#{sign}"
    {
      'Date' => date,
      'X-Amzn-Authorization' => auth,
      'Content-Type' => 'text/xml'
    }
  end
```

**Comment by starbelly** [comment]
@baelter This is merely fetching a resource record set? I ask because I'd like to mimic  (as much as possible) in order to reproduce the exception.

**Comment by baelter** [comment]
Yes, well all of them. Quite a few in my case

**Comment by starbelly** [comment]
@baelter Ok, so just a big download essentially? Are threads involved? I'll try to hop on this tomorrow btw.

**Comment by geemus** [comment]
It may be a timeout from AWS side, if it is in fact a really big response. I think connections timeout on at least some of AWS services in around 30 seconds (so I wouldn't imagine that would be the case here). That said, it might be more aggressive here. Do you have a ballpark of just how many records you are talking about? You might try running with debug turned on as well, as it may be a bit more revealing.

**Comment by starbelly** [comment]
@geemus Yeah, I figured it was a timeout issue too. Regardless, I still plan on trying to replicate so we can handle the exception gracefully, if possible.

**Comment by geemus** [comment]
@starbelly Sounds good, just let me know if you need anything.

**Comment by parkr** [comment]
Seeing this as well with much smaller payloads. Using to stream stdout from the Docker API.

**Comment by starbelly** [comment]
Sorry guys, have been quite busy. Will look at this as soon as possible.

**Comment by geemus** [comment]
@starbelly no worries, thanks for helping here as you are able.

**Comment by starbelly** [comment]
@park Can you provide some debug info? EXCON_DEBUG=true in your shell or your code before excon is loaded will do the trick.

**Comment by geemus** [comment]
Are you re-using the same connection to make many requests?

**Comment by geemus** [comment]
For clarity, I ask because in searching for similar errors online I see a few cases in which it seems this error is from server-side timeouts being triggered. ie I've had some experience with servers that close your connection after 30 seconds idle but have also seen close your connection 30 seconds after it starts, regardless of activity. In either case, if client thought there was more to read and tried to do so, you would likely see an error like this.

If that were the case though, reseting the connection prior to a request should prevent it. This is slower and more inefficient than re-use, but it should work consistently. Otherwise you could try to ensure requests happen at least on a certain interval and/or reset the connection if they haven't as an optimization (but now you are managing complexity to get the performance, so depends what is your priority).

**Comment by geemus** [comment]
Closing due to inactivity, please let us know if you are still experiencing issues though.

**Comment by angelacode** [comment]
Excon::Error::Socket: end of file reached (EOFError)

**Comment by foreverqihe** [comment]
@geemus   Can we reset automatically if the EOF happens?

**Comment by geemus** [comment]
@foreverqihe depends on your details. That is what the idempotent middleware is geared to do, but it could potentially be dangerous for write operations (it should be safe for fetch).
