### ISSUE TITLE
OpenSSL::SSL::SSLError in master tests

### ISSUE THREAD

**Issue by prog1dev** [excon/excon#686]
Checked on master [9e934d0dc169ddfd1fe08e07873a5ba2d8be7aa1](https://github.com/excon/excon/tree/9e934d0dc169ddfd1fe08e07873a5ba2d8be7aa1)
Same result with `bundle & bundle exec shindont` and [travis](https://travis-ci.org/excon/excon/jobs/439221474):
```
  Excon ssl verify peer (ssl) +    
    tests/basic_tests.rb
      Excon ssl verify peer (ssl)
    - returns 200
    
    tests/basic_tests.rb
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError) Unable to verify certificate. This may be an issue with the remote host or with Excon. Excon has certificates bundled, but these can be customized:
            `Excon.defaults[:ssl_ca_path] = path_to_certs`
            `ENV['SSL_CERT_DIR'] = path_to_certs`
            `Excon.defaults[:ssl_ca_file] = path_to_file`
            `ENV['SSL_CERT_FILE'] = path_to_file`
            `Excon.defaults[:ssl_verify_callback] = callback`
                (see OpenSSL::SSL::SSLContext#verify_callback)
or:
            `Excon.defaults[:ssl_verify_peer] = false` (less secure).
 (Excon::Error::Certificate)
      /home/travis/build/excon/excon/lib/excon/ssl_socket.rb:125:in `connect_nonblock'
      /home/travis/build/excon/excon/lib/excon/ssl_socket.rb:125:in `initialize'
      /home/travis/build/excon/excon/lib/excon/connection.rb:446:in `new'
      /home/travis/build/excon/excon/lib/excon/connection.rb:446:in `socket'
      /home/travis/build/excon/excon/lib/excon/connection.rb:116:in `request_call'
      /home/travis/build/excon/excon/lib/excon/middlewares/mock.rb:56:in `request_call'
      /home/travis/build/excon/excon/lib/excon/middlewares/instrumentor.rb:34:in `request_call'
      /home/travis/build/excon/excon/lib/excon/middlewares/idempotent.rb:18:in `request_call'
      /home/travis/build/excon/excon/lib/excon/middlewares/base.rb:22:in `request_call'
      /home/travis/build/excon/excon/lib/excon/middlewares/base.rb:22:in `request_call'
      /home/travis/build/excon/excon/lib/excon/connection.rb:270:in `request'
      tests/basic_tests.rb:151:in `block (3 levels) in <top (required)>'
      /home/travis/.rvm/gems/ruby-2.0.0-p648/gems/shindo-0.3.8/lib/shindo.rb:140:in `instance_eval'
      /home/travis/.rvm/gems/ruby-2.0.0-p648/gems/shindo-0.3.8/lib/shindo.rb:140:in `assert'
      /home/travis/.rvm/gems/ruby-2.0.0-p648/gems/shindo-0.3.8/lib/shindo.rb:112:in `returns'
      tests/basic_tests.rb:150:in `block (2 levels) in <top (required)>'
      tests/test_helper.rb:250:in `with_rackup'
      tests/basic_tests.rb:142:in `block in <top (required)>'
      /home/travis/.rvm/gems/ruby-2.0.0-p648/gems/shindo-0.3.8/lib/shindo.rb:79:in `instance_eval'
      /home/travis/.rvm/gems/ruby-2.0.0-p648/gems/shindo-0.3.8/lib/shindo.rb:79:in `tests'
      /home/travis/.rvm/gems/ruby-2.0.0-p648/gems/shindo-0.3.8/lib/shindo.rb:38:in `initialize'
      /home/travis/.rvm/gems/ruby-2.0.0-p648/gems/shindo-0.3.8/lib/shindo.rb:13:in `new'
      /home/travis/.rvm/gems/ruby-2.0.0-p648/gems/shindo-0.3.8/lib/shindo.rb:13:in `tests'
      tests/basic_tests.rb:141:in `<top (required)>'
      /home/travis/.rvm/gems/ruby-2.0.0-p648/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `load'
      /home/travis/.rvm/gems/ruby-2.0.0-p648/gems/shindo-0.3.8/lib/shindo/bin.rb:61:in `block (2 levels) in run_in_thread'
      /home/travis/.rvm/gems/ruby-2.0.0-p648/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `each'
      /home/travis/.rvm/gems/ruby-2.0.0-p648/gems/shindo-0.3.8/lib/shindo/bin.rb:58:in `block in run_in_thread'
[2018-10-09 16:22:15] ERROR OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=SSLv3 read client certificate A: sslv3 alert certificate expired
	/home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/openssl/ssl.rb:280:in `accept'
```

**Comment by voxik** [comment]
This should help, at least locally:

~~~
$ rake update_certs
~~~

**Comment by geemus** [comment]
Thanks for the heads up. Looks like the self-signed certs the test suite uses must have expired again. I've updated and pushed them, so hopefully we'll be back to green again now.
