### ISSUE TITLE
Warning: "Invalid Excon connection keys: :__construction_args"

### ISSUE THREAD

**Issue by delner** [excon/excon#705]
### The issue

When invoking a Excon request that returns an error, I'm receiving a very verbose `[excon][WARNING] Invalid Excon connection keys: :__construction_args` warning followed by a stack trace.

In a nutshell, this is happening when I add a middleware which just invokes the error stack:

```ruby
class MyMiddleware < ::Excon::Middleware::Base
  def error_call(datum)
    @stack.error_call(datum)
  end
end

# Initialize connection with middleware and timeout stub
connection = Excon.new('http://example.com', connection_options).tap do
  Excon.stub(
    { method: :get, path: '/timeout' },
    lambda do |_request_params|
      raise Excon::Errors::Timeout, 'READ TIMEOUT'
    end
  )
end

# Raises Excon::Error::Timeout as expected but also prints the warning.
connection.get(path: '/timeout', idempotent: true, retry_limit: 4)
```

If I run the [full test](https://github.com/DataDog/dd-trace-rb/blob/6d64a3467032d21dfdb199a0722ea16679a56cf4/spec/ddtrace/contrib/excon/instrumentation_spec.rb#L139) using [the original middleware source code](https://github.com/DataDog/dd-trace-rb/blob/6d64a3467032d21dfdb199a0722ea16679a56cf4/lib/ddtrace/contrib/excon/middleware.rb#L47), you can see that it is pulling in `__construction_args` from `@data` on `Excon::Connection#request`:

```
From: /usr/local/bundle/gems/excon-0.66.0/lib/excon/connection.rb @ line 232 Excon::Connection#request:

    227:     # @option params [Hash<Symbol, String>] :headers The default headers to supply in a request
    228:     # @option params [String] :path appears after 'scheme://host:port/'
    229:     # @option params [Hash]   :query appended to the 'scheme://host:port/path/' in the form of '?key=value'
    230:     def request(params={}, &block)
    231:       # @data has defaults, merge in new params to override
 => 232:       datum = @data.merge(params)
    233:       datum[:headers] = @data[:headers].merge(datum[:headers] || {})
    234: 
    235:       validate_params(:request, params, datum[:middlewares])
    236:       # If the user passed in new middleware, we want to validate that the original connection parameters
    237:       # are still valid with the provided middleware.

[1] pry(#<Excon::Connection>)> params
=> {:chunk_size=>1048576,
 :debug_request=>false,
 :debug_response=>false,
 :headers=>
  {"User-Agent"=>"excon/0.66.0",
   "Accept"=>"*/*",
   "Host"=>"example.com:80",
   "x-datadog-trace-id"=>"1133160354822024889",
   "x-datadog-parent-id"=>"3861050759971055527"},
 :idempotent=>true,
 :instrumentor_name=>"excon",
 :middlewares=>
  [Excon::Middleware::ResponseParser,
   Datadog::Contrib::Excon::Middleware,
   Excon::Middleware::Expects,
   Excon::Middleware::Idempotent,
   Excon::Middleware::Instrumentor,
   Excon::Middleware::Mock],
 :mock=>true,
 :persistent=>false,
 :read_timeout=>60,
 :retry_errors=>[Excon::Error::Timeout, Excon::Error::Socket, Excon::Error::HTTPStatus],
 :retry_limit=>4,
 :stubs=>:global,
 :versions=>"excon/0.66.0 (x86_64-linux) ruby/2.3.8",
 :write_timeout=>60,
 :path=>"/timeout",
 :query=>nil,
 :retries_remaining=>2,
 :captures=>{:headers=>{}},
 :method=>:get}

From: /usr/local/bundle/gems/excon-0.66.0/lib/excon/connection.rb @ line 238 Excon::Connection#request:

    233:       datum[:headers] = @data[:headers].merge(datum[:headers] || {})
    234: 
    235:       validate_params(:request, params, datum[:middlewares])
    236:       # If the user passed in new middleware, we want to validate that the original connection parameters
    237:       # are still valid with the provided middleware.
 => 238:       if params[:middlewares]
    239:         validate_params(:connection, @data, datum[:middlewares])
    240:       end
    241: 
    242:       if datum[:user] || datum[:password]
    243:         user, pass = Utils.unescape_uri(datum[:user].to_s), Utils.unescape_uri(datum[:password].to_s)

[1] pry(#<Excon::Connection>)> @data
=> {:chunk_size=>1048576,
 :ciphers=>
  "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA:!DSS",
 :connect_timeout=>60,
 :debug_request=>false,
 :debug_response=>false,
 :headers=>{"User-Agent"=>"excon/0.66.0", "Accept"=>"*/*"},
 :idempotent=>false,
 :instrumentor_name=>"excon",
 :middlewares=>
  [Excon::Middleware::ResponseParser,
   Datadog::Contrib::Excon::Middleware,
   Excon::Middleware::Expects,
   Excon::Middleware::Idempotent,
   Excon::Middleware::Instrumentor,
   Excon::Middleware::Mock],
 :mock=>true,
 :nonblock=>true,
 :omit_default_port=>false,
 :persistent=>false,
 :read_timeout=>60,
 :retry_errors=>[Excon::Error::Timeout, Excon::Error::Socket, Excon::Error::HTTPStatus],
 :retry_limit=>4,
 :ssl_verify_peer=>true,
 :ssl_uri_schemes=>["https"],
 :stubs=>:global,
 :tcp_nodelay=>false,
 :thread_safe_sockets=>true,
 :uri_parser=>URI,
 :versions=>"excon/0.66.0 (x86_64-linux) ruby/2.3.8",
 :write_timeout=>60,
 :host=>"example.com",
 :hostname=>"example.com",
 :path=>"",
 :port=>80,
 :query=>nil,
 :scheme=>"http",
 :__construction_args=>{:host=>"example.com", :hostname=>"example.com", :path=>"", :port=>80, :query=>nil, :scheme=>"http", :mock=>true}}
[2] pry(#<Excon::Connection>)> continue
[excon][WARNING] Invalid Excon connection keys: :__construction_args
/usr/local/bundle/gems/excon-0.66.0/lib/excon/connection.rb:425:in `validate_params'
/usr/local/bundle/gems/excon-0.66.0/lib/excon/connection.rb:239:in `request'
/usr/local/bundle/gems/excon-0.66.0/lib/excon/middlewares/idempotent.rb:50:in `error_call'
/usr/local/bundle/gems/excon-0.66.0/lib/excon/middlewares/base.rb:17:in `error_call'
/app/lib/ddtrace/contrib/excon/middleware.rb:49:in `error_call'
```

### Additional considerations

Is it at all related to the changes in [this commit](https://github.com/excon/excon/commit/e2820ba8ecd312d653b7ca92ab8c24a80fbce6e6#diff-93618fc68cdc1fde818cf4abd7102a14R239)?

We also see a similar warning with another test that doesn't raise an error:

```
[excon][WARNING] Invalid Excon connection keys: :idempotent, :instrumentor_name, :retry_errors, :retry_limit
/usr/local/bundle/gems/excon-0.66.0/lib/excon/connection.rb:425:in `validate_params'
/usr/local/bundle/gems/excon-0.66.0/lib/excon/connection.rb:71:in `initialize'
/usr/local/bundle/gems/webmock-2.3.2/lib/webmock/http_lib_adapters/excon_adapter.rb:157:in `new'
/usr/local/bundle/gems/webmock-2.3.2/lib/webmock/http_lib_adapters/excon_adapter.rb:157:in `new'
/usr/local/bundle/gems/excon-0.66.0/lib/excon.rb:142:in `new'
/app/spec/ddtrace/contrib/excon/instrumentation_spec.rb:38:in `block (2 levels) in <top (required)>'
/app/spec/ddtrace/contrib/excon/instrumentation_spec.rb:262:in `block (3 levels) in <top (required)>'
```

However, this one has WebMock involved, and occurs under different circumstances (successful request, not idempotent, etc.), so it's unclear whether it's related or not.

Are we somehow mishandling `@data` or doing something in [our middleware](https://github.com/DataDog/dd-trace-rb/blob/6d64a3467032d21dfdb199a0722ea16679a56cf4/lib/ddtrace/contrib/excon/middleware.rb) we're not supposed to?

**Comment by geemus** [comment]
Hey, sorry to hear you are having difficulties.

I tried to duplicate your problem with the sample script you provided, but it doesn't actually include the assignment of `connection_options`. If I remove that, it seems to work without raising any error. Could you try that and/or let me know what connection options you are using that result in the error so I can duplicate? Thanks!

**Comment by delner** [comment]
Yeah the sample script isn't a fully comprehensive test; it's derived from one our unit tests that are presenting the issue. All of that code is open source, and if you were so inclined, I could share you instructions to run that in earnest yourself, but I can understand that might be asking a bit much, hence why I tried to slim things down into a simpler example.

Do you have any suggestions as to why `@data` reintroduces `:__construction_args` when calling request? If I understood how that state was set, I could walk back through the test and code to figure out if we might have been using things improperly.

That said, if necessary, I could try to create fully runnable test derived from the one that presented the issue, but that will take some time (hence the alternative offered to run our open source tests.)

**Comment by geemus** [comment]
Ah ok, I misunderstood the purpose of the snippet.

Do you know where `:__construction_args` is coming from in the first place? I don't think that would be from inside excon itself.

The merge there is so that the connection level settings and request level settings will merge together to get the final full set of attributes for the call. Does that help? It should just merge it whatever is passed, which I don't think should include `:__construction_args` unless that was passed in from somewhere else.

Does that help?

**Comment by delner** [comment]
No idea; I thought `:__construction_args` might be an Excon thing. We don't use this, so maybe it's some HTTP stub library in our test suite? I'll check on this.

But from the second example `:idempotent, :instrumentor_name, :retry_errors, :retry_limit` are all legitimate options no? WebMock looks like it's in play there, but trying to understand the circumstances of why these options would be considered invalid at this point.
