### ISSUE TITLE
Exception if no_proxy includes IPv6-address

### ISSUE THREAD

**Issue by m-bucher** [excon/excon#716]
If the `no_proxy` environment variable includes an IPv6-address with brackets, excon raises an exception:
```
$ export no_proxy=[::1],localhost,127.0.0.1
$ irb
2.6.3 :001 > require 'excon'
 => true 
2.6.3 :002 > con = Excon.new('http://localhost/')
Traceback (most recent call last):
       11: from /usr/share/rvm/rubies/ruby-2.6.3/bin/irb:23:in `<main>'
       10: from /usr/share/rvm/rubies/ruby-2.6.3/bin/irb:23:in `load'
        9: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        8: from (irb):4
        7: from (irb):4:in `rescue in irb_binding'
        6: from /home/user/.rvm/gems/ruby-2.6.3/gems/excon-0.73.0/lib/excon.rb:142:in `new'
        5: from /home/user/.rvm/gems/ruby-2.6.3/gems/excon-0.73.0/lib/excon.rb:142:in `new'
        4: from /home/user/.rvm/gems/ruby-2.6.3/gems/excon-0.73.0/lib/excon/connection.rb:78:in `initialize'
        3: from /home/user/.rvm/gems/ruby-2.6.3/gems/excon-0.73.0/lib/excon/connection.rb:504:in `setup_proxy'
        2: from /home/user/.rvm/gems/ruby-2.6.3/gems/excon-0.73.0/lib/excon/connection.rb:504:in `index'
        1: from /home/user/.rvm/gems/ruby-2.6.3/gems/excon-0.73.0/lib/excon/connection.rb:504:in `block in setup_proxy'
RegexpError (premature end of char-class: /(^|\.)[$/)
```

**Comment by geemus** [comment]
Thanks for the heads up, I wasn't previously aware of this, but looking at the code and tests it looks as though we hadn't yet considered IPv6 when it was written. Would you be interested in working on a patch to help fix this?
