### ISSUE TITLE
"local port can be re-bound" test fails when there is just local host

### ISSUE THREAD

**Issue by voxik** [excon/excon#737]
There was one unresolved issue mentioned in https://github.com/excon/excon/issues/733#issuecomment-781504745:

~~~
  Excon basics (reusable local port) (reusable) +    
    /builddir/build/BUILD/excon-0.79.0/usr/share/gems/gems/excon-0.79.0/tests/basic_tests.rb
      Excon basics (reusable local port) (reusable)
    - returns "xxxxxxxxxx"
    
    /builddir/build/BUILD/excon-0.79.0/usr/share/gems/gems/excon-0.79.0/tests/basic_tests.rb
    Cannot assign requested address - connect(2) for 127.0.0.1:9292 (Errno::EADDRNOTAVAIL)
      /builddir/build/BUILD/excon-0.79.0/usr/share/gems/gems/excon-0.79.0/tests/basic_tests.rb:320:in `connect'
      /builddir/build/BUILD/excon-0.79.0/usr/share/gems/gems/excon-0.79.0/tests/basic_tests.rb:320:in `connect'
      /builddir/build/BUILD/excon-0.79.0/usr/share/gems/gems/excon-0.79.0/tests/basic_tests.rb:360:in `block (3 levels) in <top (required)>'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:139:in `instance_eval'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:139:in `assert'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:111:in `returns'
      /builddir/build/BUILD/excon-0.79.0/usr/share/gems/gems/excon-0.79.0/tests/basic_tests.rb:352:in `block (2 levels) in <top (required)>'
      tests/test_helper.rb:250:in `with_rackup'
      /builddir/build/BUILD/excon-0.79.0/usr/share/gems/gems/excon-0.79.0/tests/basic_tests.rb:341:in `block in <top (required)>'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:79:in `instance_eval'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:79:in `tests'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:38:in `initialize'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:13:in `new'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:13:in `tests'
      /builddir/build/BUILD/excon-0.79.0/usr/share/gems/gems/excon-0.79.0/tests/basic_tests.rb:305:in `<top (required)>'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo/bin.rb:61:in `load'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo/bin.rb:61:in `block (2 levels) in run_in_thread'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo/bin.rb:58:in `each'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo/bin.rb:58:in `block in run_in_thread'
~~~

And now I understand the issue. This is the scenario, when the test case passes:

~~~
$ ruby -rsocket -e 'p Socket.ip_address_list'
[#<Addrinfo: 127.0.0.1>, #<Addrinfo: 192.168.0.90>, #<Addrinfo: 192.168.122.1>, #<Addrinfo: 10.36.112.21>, #<Addrinfo: 192.168.0.45>, #<Addrinfo: ::1>, #<Addrinfo: fe80::70ad:a8f7:777a:e3b5%wlp0s20f3>, #<Addrinfo: fe80::b6cf:b798:6764:bfd7%tun0>, #<Addrinfo: fe80::3ee1:a1ff:fec3:89b6%enp0s20f0u2u1u2>]
~~~

And this is when it fails:

~~~
$ ruby -rsocket -e 'p Socket.ip_address_list'
[#<Addrinfo: 127.0.0.1>, #<Addrinfo: ::1>]
~~~

This is the scenario testing in container with disabled networking. Because there is no alternative IP address, the following condition cannot be fulfilled:

https://github.com/excon/excon/blob/b062b10a9eb034cf3ea89f5343c7687f5aa0be70/tests/basic_tests.rb#L354-L357

I think that the following method should be updated:

https://github.com/excon/excon/blob/b062b10a9eb034cf3ea89f5343c7687f5aa0be70/tests/basic_tests.rb#L332-L334

because the fallback to `127.0.0.1` probably doesn't make sense. If there is no alternative address, the test will fail anyway. Therefore the test should be rather failed or skipped.

**Comment by geemus** [comment]
@voxik thanks for the detailed report. I dropped the default as per your suggestion, and changed that particular test to be pending status if no other ips are available. Just let me know if you have any questions or concerns.
Thanks!

**Comment by voxik** [comment]
The test suite is passing now. Thx a lot!

**Comment by geemus** [comment]
@voxik Awesome, thanks again for all your help!
