### ISSUE TITLE
Can't `#unstub` request with path regexp

### ISSUE THREAD

**Issue by dentarg** [excon/excon#815]
```ruby
$ irb -rexcon
irb(main):001:0> request_params = { path: %r{/api/metadata} }
=> {:path=>/\/api\/metadata/}
irb(main):002:0> response_params = { status: 200, body: "OK" }
=> {:status=>200, :body=>"OK"}
irb(main):003:0> Excon.stub(request_params, response_params)
=> [{:path=>/\/api\/metadata/}, {:status=>200, :body=>"OK"}]
irb(main):004:0> Excon.get("http://www.google.com/api/metadata", mock: true)
=> #<Excon::Response:0x000000010d72eb20 @body="OK", @data={:body=>"OK", :headers=>{}, :status=>200, :remote_ip=>"127.0.0.1"}, @headers={}, @local_address=nil, @local_port=nil, @remote_ip="127.0.0.1", @status=200>
irb(main):005:0> Excon.unstub(request_params)
/Users/dentarg/.rubies/3.2.0/lib/ruby/gems/3.2.0/gems/excon-0.98.0/lib/excon.rb:212:in `match': no implicit conversion of Regexp into String (TypeError)

            if (match = value.match(request_params[key]))
                                    ^^^^^^^^^^^^^^^^^^^
	from /Users/dentarg/.rubies/3.2.0/lib/ruby/gems/3.2.0/gems/excon-0.98.0/lib/excon.rb:212:in `block (2 levels) in stub_for'
	from /Users/dentarg/.rubies/3.2.0/lib/ruby/gems/3.2.0/gems/excon-0.98.0/lib/excon.rb:209:in `all?'
	from /Users/dentarg/.rubies/3.2.0/lib/ruby/gems/3.2.0/gems/excon-0.98.0/lib/excon.rb:209:in `block in stub_for'
	from /Users/dentarg/.rubies/3.2.0/lib/ruby/gems/3.2.0/gems/excon-0.98.0/lib/excon.rb:196:in `each'
	from /Users/dentarg/.rubies/3.2.0/lib/ruby/gems/3.2.0/gems/excon-0.98.0/lib/excon.rb:196:in `stub_for'
	from /Users/dentarg/.rubies/3.2.0/lib/ruby/gems/3.2.0/gems/excon-0.98.0/lib/excon.rb:242:in `unstub'
	from (irb):5:in `<main>'
	from /Users/dentarg/.rubies/3.2.0/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from /Users/dentarg/.rubies/3.2.0/bin/irb:25:in `load'
	from /Users/dentarg/.rubies/3.2.0/bin/irb:25:in `<main>'
```

**Comment by geemus** [comment]
Thanks for the detailed report, I guess we must have overlooked that previously.

I added a test and a fix, and it should be released as part of v0.99.0.
