### ISSUE TITLE
Excon 0.111 seems to break Chef Client execution

### ISSUE THREAD

**Issue by isaitgirl** [excon/excon#852]
Hello!

Today the execution of `docker` Chef Cookbook seems to stop functioning with error:

```
FrozenError
-----------
can't modify frozen Array: [:allow_unstubbed_requests, :body, :chunk_size, :debug_request, :debug_response, :dns_timeouts, :headers, :instrumentor, :logger, :method, :middlewares, :password, :path, :persistent, :pipeline, :query, :read_timeout, :request_block, :resolv_resolver, :response_block, :stubs, :timeout, :user, :versions, :write_timeout]

Cookbook Trace: (most recent call first)
----------------------------------------
  /var/chef/cache/cookbooks/docker/libraries/docker_base.rb:3:in `<class:DockerBase>'
  /var/chef/cache/cookbooks/docker/libraries/docker_base.rb:2:in `<module:DockerCookbook>'
  /var/chef/cache/cookbooks/docker/libraries/docker_base.rb:1:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/docker/libraries/docker_base.rb:

  1:  module DockerCookbook
  2:    class DockerBase < Chef::Resource
  3>>     require 'docker'
  4:      require 'shellwords'
  5:
  6:      ################
  7:      # Helper methods
  8:      ################
  9:
 10:      def connection
 11:        @connection ||= begin
 12:                          opts = {}
```

Stack trace mentions first point as excon, 0.111:

```
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/excon/middlewares/hijack.rb:2:in `<module:Excon>': can't modify frozen Array: [:allow_unstubbed_requests, :body, :chunk_size, :debug_request, :debug_response, :dns_timeouts, :headers, :instrumentor, :logger, :method, :middlewares, :password, :path, :persistent, :pipeline, :query, :read_timeout, :request_block, :resolv_resolver, :response_block, :stubs, :timeout, :user, :versions, :write_timeout] (FrozenError)
	from /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/docker-api-2.2.0/lib/excon/middlewares/hijack.rb:1:in `<top (required)>'
	from <internal:/opt/chef/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/chef/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

The only files modified today, 2024-07-08 in the filesystem are excon files:

```
# find -type f -mtime 0
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/CONTRIBUTING.md
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/CONTRIBUTORS.md
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/LICENSE.md
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/README.md
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/data/cacert.pem
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/excon.gemspec
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/connection.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/constants.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/error.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/extensions/uri.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/headers.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/instrumentors/logging_instrumentor.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/instrumentors/standard_instrumentor.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/middlewares/base.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/middlewares/capture_cookies.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/middlewares/decompress.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/middlewares/escape_path.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/middlewares/expects.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/middlewares/idempotent.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/middlewares/instrumentor.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/middlewares/mock.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/middlewares/redirect_follower.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/middlewares/response_parser.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/pretty_printer.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/response.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/socket.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/ssl_socket.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/test/plugin/server/exec.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/test/plugin/server/puma.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/test/plugin/server/unicorn.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/test/plugin/server/webrick.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/test/server.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/unix_socket.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/utils.rb
./embedded/lib/ruby/gems/3.0.0/gems/excon-0.111.0/lib/excon/version.rb
./embedded/lib/ruby/gems/3.0.0/specifications/excon-0.111.0.gemspec
./embedded/lib/ruby/gems/3.0.0/cache/excon-0.111.0.gem
```

chef_version=17.10.122
platform=rocky
platform_version=9.0
ruby=ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
program_name=/usr/bin/chef-shell
executable=/opt/chef/bin/chef-shell

Do you have any direction to help me to understand whether excon update really impacted this ecossystem?

Thanks in advance!

Best regards,
Isadora.

**Comment by geemus** [comment]
Hey, sorry to hear about this. It looks like it is an unfortunate interaction between the updates in excon and the usage inside the docker-api gem. It appears docker-api fixed it just a few hours ago though, so if you update that it should get you back to good working condition again. The discussion around that issue can be found here, fwiw: https://github.com/upserve/docker-api/issues/586

Just let me know if you have further questions or feedback.
