### ISSUE TITLE
RedirectFollower erroring out 

### ISSUE THREAD

**Issue by foca** [excon/excon#853]
```
▸ irb -r excon
>> Excon.get("http://google.com", {middlewares: [Excon::Middleware::RedirectFollower]})
/Users/foca/.gem/ruby/3.3.4/gems/excon-0.111.0/lib/excon/response.rb:216:in `merge': no implicit conversion of nil into Hash (TypeError)

      }.merge(params)
              ^^^^^^
        from /Users/foca/.gem/ruby/3.3.4/gems/excon-0.111.0/lib/excon/response.rb:216:in `initialize'
        from /Users/foca/.gem/ruby/3.3.4/gems/excon-0.111.0/lib/excon/connection.rb:310:in `new'
        from /Users/foca/.gem/ruby/3.3.4/gems/excon-0.111.0/lib/excon/connection.rb:310:in `request'
        from /Users/foca/.gem/ruby/3.3.4/gems/excon-0.111.0/lib/excon.rb:250:in `get'
        from (irb):1:in `<main>'
        from <internal:kernel>:187:in `loop'
        from /Users/foca/.gem/ruby/3.3.4/gems/irb-1.14.0/exe/irb:9:in `<top (required)>'
        from /Users/foca/.gem/ruby/3.3.4/bin/irb:25:in `load'
        from /Users/foca/.gem/ruby/3.3.4/bin/irb:25:in `<main>'
>> Excon::VERSION
=> "0.111.0"
```

**Comment by geemus** [comment]
Hey, sorry to hear you ran into this.

I believe the issue may stem from this using ONLY the redirect follower middleware, as there are some others that are expected to be in place as well. I think the invocation you are after would be more like:

`Excon.get("http://google.com", {middlewares: Excon.defaults[:middlewares] + [Excon::Middleware::RedirectFollower]})`

That will keep all the expected middlewares in place and add the redirectfollower in.

Whether or not this is ideal is perhaps a bigger question, but as it stands that should get it working for you (and improving it would probably be a breaking change, which brings it's own challenges).

**Comment by foca** [comment]
Oh, doh. I feel dumb now. That was obviously it.

> Whether or not this is ideal is perhaps a bigger question, but as it stands that should get it working for you (and improving it would probably be a breaking change, which brings it's own challenges).

Yeah, for sure. There might be a middle ground approach by adding a new key, like `add_middlewares:` or similar, that keeps the API relatively neat without introducing any backwards incompatibility. But also concatenating the arrays manually isn't terrible, so ¯\\_(ツ)\_/¯ 

Thanks!

**Comment by geemus** [comment]
Yeah, I'd like to continue to improve it, but it's also basically been "good enough" so far.

Glad to hear that solved it for you.
